### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tyrohellion** [Chr1sDev/Atlas#3]
I think myself and a lot of others would love to see IOS 13 support from this tweak, if not we understand :)

**Comment by ChristopherA8** [comment]
I gotchu

**Comment by ChristopherA8** [comment]
To clarify, the version on packix works for arm64 devices on iOS 13-15(I haven't tried it on 15)
if you have an arm64e device on iOS 13, I can recompile it with xcode 11 instead of xcode 12 and that will fix the issue with the preference bundle not working. The best solution as of right now would be to include both versions of the tweak and then use some sort of postinst script or loader to install the specific version for your device

**Comment by tyrohellion** [comment]
I tried the tweak from packix on an iphone x running IOS 13.2 and after installing I get stuck in respring animation and after je-jailbreaking after a boot I get stuck at the boot logo
